# Generated by Django 4.1.7 on 2023-05-09 10:55

import Loan.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "devolution_date",
                    models.DateField(default=Loan.models.generate_devolution_date),
                ),
                ("is_returned", models.BooleanField(default=False)),
                (
                    "copy_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copy_loaned",
                        to="Book.copy",
                    ),
                ),
            ],
        ),
    ]
