# Generated by Django 4.1.7 on 2023-05-07 14:00

import Loan.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Loan", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="devolution_date",
            field=models.DateField(default=Loan.models.generate_devolution_date),
        ),
    ]
